# it is faster than UI, syncs faster
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd  # name space where argoCd pods are running, this is how if identifies in which argocd to deploy
spec:
  project: default

  source:
    repoURL: https://github.com/debasish2110/kubernetes.git
    targetRevision: HEAD
    path: 7_ArgoCd
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp  # app pod will be created under myapp namespace

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
